version: '3.0'

env:
  ENV: dev

tasks:
  
  dev:server:
    desc: "Run Go backend"
    cmds:
      - cd server && go run cmd/server/main.go
    silent: true

  dev:mock:
    desc: "Run Node.js mock server"
    cmds:
      - cd location/mock-server && npm run start
    silent: true
  
  dev:ingest:
    desc: "Run Ingest Server"
    cmds:
      - cd location/ingest-server && go run main.go
    silent: true

  dev:consumer:
    desc: "Run Consumer Worker"
    cmds:
      - cd location/consumer-worker && go run main.go
    silent: true
  
  dev:websocket:
    desc: "Run Websocket Server"
    cmds:
      - cd location/Websocket && go run main.go
    silent: true